const PHONE = "+37493511288"
const WA_LINK = "https://wa.me/37493511288"
const FB_LINK = "https://www.facebook.com/profile.php?id=100069396610679"
const IG_LINK = "https://www.instagram.com/mirage_naritoys"

const products = [
  {
    id: 1,
    tag: "Սկյուռ",
    name: "Սկյուռիկ",
    shortDesc: "Սկյուռիկ կանաչ սվիտերով ու շարֆով։ Կախովի զարդ։",
    fullDesc: "Ձեռագործ պապյե մաշե սկյուռիկ՝ կանաչ սվիտերով, նախշավոր շարֆով ու ուսապարկով։ Ամեն մանրամասնը ձեռքով է ներկված ու եզակի է։\n\nSquirrel in green sweater with a scarf and backpack. Handmade papier-mache, each piece is unique.",
    price: "֏ 12,000",
    sizes: ["Բարձրություն՝ ~15 սմ","Լայնություն՝ ~6 սմ"],
    images: ["images/mirage/squirrel/1.jpg","images/mirage/squirrel/2.jpg","images/mirage/squirrel/3.jpg","images/mirage/squirrel/4.jpg","images/mirage/squirrel/5.jpg","images/mirage/squirrel/6.jpg","images/mirage/squirrel/7.jpg"],
    video: "images/mirage/squirrel/video.mov",
  },
  {
    id: 2,
    tag: "Կենդանի",
    name: "Պանդա լուսնի վրա",
    shortDesc: "Պանդա նստած նարնջագույն լուսնի վրա։ Կախովի զարդ։",
    fullDesc: "Սիրուն պանդան նստած նարնջագույն լուսնի վրա, ծաղիկներով։ Ձեռագործ պապյե մաշե։ Հարմար նվեր երեխաների համար։\n\nPanda sitting on an orange crescent moon with flowers. Handmade papier-mache. A lovely gift for children.",
    price: "֏ 10,000",
    sizes: ["Բարձրություն՝ ~12 սմ","Լայնություն՝ ~10 սմ"],
    images: ["images/mirage/panda/1.jpg","images/mirage/panda/2.jpg", "images/mirage/panda/3.jpg"],
    video: "images/mirage/panda/video.mov",
  },
  {
    id: 3,
    tag: "Կենդանի",
    name: "Աղվեսիկ",
    shortDesc: "Նարնջագույն աղվեսիկ շարֆով, չմուշկների վրա։ Կախովի զարդ։",
    fullDesc: "Նարնջագույն աղվեսիկ վիշնագույն շարֆով, չմուշկների վրա։ Կախովի զարդ, ձեռագործ պապյե մաշե։\n\nOrange fox with a checkered scarf, ice skating. Hanging ornament, handmade papier-mache.",
    price: "֏ 10,000",
    sizes: ["Բարձրություն՝ ~14 սմ","Լայնություն՝ ~7 սմ"],
    images: ["images/mirage/fox/1.jpg","images/mirage/fox/2.jpg","images/mirage/fox/3.jpg","images/mirage/fox/4.jpg"],
    video: "images/mirage/fox/video.mov",
  },
  {
    id: 4,
    tag: "Կենդանի",
    name: "Փիղ գնդակի վրա",
    shortDesc: "Փիղ գունավոր կետավոր գնդակի վրա։",
    fullDesc: "Կրկեսային փիղ, նստած գունավոր կետավոր գնդակի վրա։ Կախովի զարդ, ձեռագործ պապյե մաշե։\n\nCircus elephant balancing on a colorful polka-dot ball. Hanging ornament, handmade papier-mache.",
    price: "֏ 10,000",
    sizes: ["Բարձրություն՝ ~12 սմ","Լայնություն՝ ~8 սմ"],
    images: ["images/mirage/elephant/1.jpg","images/mirage/elephant/2.jpg","images/mirage/elephant/3.jpg","images/mirage/elephant/4.jpg"],
    video: "images/mirage/elephant/video.mov",
  },
  {
    id: 5,
    tag: "Տոնական",
    name: "Նվեր բերող էլֆ",
    shortDesc: "Կանաչ էլֆիկ նվերի տուփով։ Տոնական զարդ։",
    fullDesc: "Կանաչ էլֆիկ ոսկե զգեստով ու նվերի տուփով, վազում է։ Ձեռագործ պապյե մաշե։ Տոնական նվեր։\n\nGreen elf running with a gift box. Gold accents. Handmade papier-mache, a festive ornament.",
    price: "֏ 9,500",
    sizes: ["Բարձրություն՝ ~14 սմ","Լայնություն՝ ~6 սմ"],
    images: ["images/mirage/gift-elf/1.jpg","images/mirage/gift-elf/2.jpg","images/mirage/gift-elf/3.jpg","images/mirage/gift-elf/4.jpg","images/mirage/gift-elf/5.jpg"],
    video: "images/mirage/gift-elf/video.mov",
  },
  {
    id: 6,
    tag: "Տիկնիկ",
    name: "Կարմիր աղջիկ",
    shortDesc: "Աղջիկ կարմիր զգեստով, դեղին օձիակով։ Կախովի զարդ։",
    fullDesc: "Աղջիկ կարմիր զգեստով, դեղին օձիակով ու կապույտ աչքերով։ Ձեռագործ պապյե մաշե։\n\nGirl in red outfit with yellow collar and blue eyes, holding a golden horn. Handmade papier-mache.",
    price: "֏ 9,000",
    sizes: ["Բարձրություն՝ ~13 սմ","Լայնություն՝ ~5 սմ"],
    images: ["images/mirage/red-girl/1.jpg","images/mirage/red-girl/2.jpg","images/mirage/red-girl/3.jpg","images/mirage/red-girl/4.jpg"],
    video: "images/mirage/red-girl/video.mov",
  },
  {
    id: 7,
    tag: "Ծաղրածու",
    name: "Կանաչ ծաղրածու",
    shortDesc: "Ծաղրածու կանաչ զգեստով, շարֆով։ Կախովի զարդ։",
    fullDesc: "Ծաղրածու կանաչ կոստյումով, նարնջագույն կոճակներով ու շարֆով։ Կապույտ քթով, կախովի զարդ։\n\nGreen clown in baggy costume with scarf and orange buttons. Blue nose, hanging ornament. Handmade papier-mache.",
    price: "֏ 8,500",
    sizes: ["Բարձրություն՝ ~14 սմ","Լայնություն՝ ~5 սմ"],
    images: ["images/mirage/green-clown/1.jpg","images/mirage/green-clown/2.jpg","images/mirage/green-clown/3.jpg"],
    video: "images/mirage/green-clown/video.mov",
  },
  {
    id: 8,
    tag: "Ծաղրածու",
    name: "Դեղին ծաղրածու",
    shortDesc: "Դեղին ծաղրածու կարմիր շարֆով։",
    fullDesc: "Դեղին ծաղրածու կարմիր շարֆով ու ձեռնոցներով։ Կախովի զարդ, ձեռագործ պապյե մաշե։\n\nYellow clown with red scarf and gloves. Smiling face, hanging ornament. Handmade papier-mache.",
    price: "֏ 8,500",
    sizes: ["Բարձրություն՝ ~14 սմ","Լայնություն՝ ~5 սմ"],
    images: ["images/mirage/yellow-clown/1.jpg","images/mirage/yellow-clown/2.jpg","images/mirage/yellow-clown/3.jpg","images/mirage/yellow-clown/4.jpg"],
    video: "images/mirage/yellow-clown/video.mov",
  },
  {
    id: 9,
    tag: "Տիկնիկ",
    name: "Բալերինա",
    shortDesc: "Բալերինա դեղին տուտուով, ծաղիկներով մազերում։",
    fullDesc: "Բալերինա դեղին տուտուով ու ծաղիկներով մազերում։ Նրբագեղ կեցվածք ու նազիկ դեմք։ Կախովի զարդ։\n\nBallerina in yellow tutu with flowers in her hair. Elegant pose, delicate face. Handmade papier-mache.",
    price: "֏ 9,500",
    sizes: ["Բարձրություն՝ ~16 սմ","Լայնություն՝ ~5 սմ"],
    images: ["images/mirage/ballerina/1.jpg","images/mirage/ballerina/2.jpg","images/mirage/ballerina/3.jpg","images/mirage/ballerina/4.jpg","images/mirage/ballerina/5.jpg"],
    video: "images/mirage/ballerina/video.mov",
  },
  {
    id: 10,
    tag: "Տիկնիկ",
    name: "Փոքրիկ երեխա",
    shortDesc: "Փոքրիկ երեխա մոխրագույն զգեստով, սպիտակ թևերով։",
    fullDesc: "Փոքրիկ երեխա մոխրագույն զգեստով ու սպիտակ թևերով։ Ձեռագործ պապյե մաշե, եզակի կտոր։\n\nBaby boy in grey pajamas with angel wings, curly hair. Handmade papier-mache, each piece is unique.",
    price: "֏ 8,000",
    sizes: ["Բարձրություն՝ ~10 սմ","Լայնություն՝ ~5 սմ"],
    images: ["images/mirage/angel-baby/3.jpg","images/mirage/angel-baby/2.jpg","images/mirage/angel-baby/1.jpg","images/mirage/angel-baby/4.jpg"],
    video: null,
  },
  {
    id: 11,
    tag: "Դեկոր",
    name: "Կապույտ կախարդ",
    shortDesc: "Կապույտ կախարդ լուսավոր գնդակով։ Կախովի զարդ։",
    fullDesc: "Կապույտ կախարդ՝ կապույտ զգեստով ու լուսավոր գնդակով։ Կարող է լուսավորել սենյակը։\n\nBlue wizard holding a glowing orb. Handmade papier-mache, lights up the room.",
    price: "֏ 14,000",
    sizes: ["Բարձրություն՝ ~18 սմ","Լայնություն՝ ~8 սմ"],
    images: ["images/mirage/blue-wizard/1.jpg","images/mirage/blue-wizard/2.jpg"],
    video: "images/mirage/blue-wizard/video.mov",
  },
]
